#!/usr/bin/env node
// Adjoin build: emits dist/tokens.css, dist/tokens.d.ts, dist/index.ts and dist/css-vars.json.
// Default is strict (any error fails). `--lenient` skips tokens whose references are broken and
// still writes output, so CI can show every downstream failure of a bad rename at once.
import { mkdirSync, writeFileSync } from "node:fs";
import { loadResolver, flatten, resolveAll, permutations, defaultInputs, permKey, Report, cssName, publicPath } from "./lib/tokens.mjs";

const RESOLVER = "tokens/adjoin.resolver.json";
const LENIENT = process.argv.includes("--lenient");
const OUT = "dist";
const report = new Report();
const { layers } = loadResolver(RESOLVER, report);
if (!layers) fail();

const modifiers = layers.filter(l => l.kind === "modifier");
const defaults = defaultInputs(layers);
const isPrimitive = t => t.origin.kind === "set" && t.origin.name === "primitives";
const aliasOf = v => typeof v === "string" && v.match(/^\{([^{}]+)\}$/)?.[1];

// ---------- formatting ----------
const GENERIC_FONTS = ["system-ui", "-apple-system", "sans-serif", "serif", "monospace", "ui-monospace", "ui-sans-serif"];
function fmt(type, v) {
  switch (type) {
    case "color": {
      if (!v.hex) throw new Error("color needs a hex fallback for CSS output");
      if (v.alpha === undefined || v.alpha === 1) return v.hex.toLowerCase();
      const [r, g, b] = [1, 3, 5].map(i => parseInt(v.hex.slice(i, i + 2), 16));
      return `rgb(${r} ${g} ${b} / ${v.alpha})`;
    }
    case "dimension": case "duration": return `${v.value}${v.unit}`;
    case "fontFamily": return (Array.isArray(v) ? v : [v]).map(f => GENERIC_FONTS.includes(f) ? f : `"${f}"`).join(", ");
    default: return String(v);
  }
}
const TYPO_PARTS = [["fontFamily", "font-family"], ["fontSize", "font-size"], ["fontWeight", "font-weight"], ["lineHeight", "line-height"], ["letterSpacing", "letter-spacing"]];
const featureOf = t => t.extensions?.["com.adjoin.css"]?.fontFeatureSettings;

// CSS declarations for one token. Aliases stay as var() so modes cascade.
function declare(t, tokens, resolved) {
  const name = cssName(t.path);
  const r = resolved.get(t.path);
  if (!r) return [];
  const target = aliasOf(t.value);
  if (r.type === "typography") {
    const src = target ? cssName(target) : null;
    const lines = TYPO_PARTS.map(([k, css]) => {
      const sub = src ? `var(${src}-${css})` : (aliasOf(t.value[k]) ? `var(${cssName(aliasOf(t.value[k]))})` : fmt(typeOfPart(k), t.value[k]));
      return [`${name}-${css}`, sub];
    });
    const feat = src ? `var(${src}-font-feature-settings)` : (featureOf(t) ?? "normal");
    lines.push([`${name}-font-feature-settings`, feat]);
    lines.push([name, src ? `var(${src})` : `var(${name}-font-weight) var(${name}-font-size)/var(${name}-line-height) var(${name}-font-family)`]);
    return lines;
  }
  if (target) return [[name, `var(${cssName(target)})`]];
  return [[name, fmt(r.type, r.value)]];
}
const typeOfPart = k => ({ fontFamily: "fontFamily", fontSize: "dimension", fontWeight: "fontWeight", lineHeight: "number", letterSpacing: "dimension" })[k];

// ---------- collect ----------
const base = flatten(layers, defaults, report);
const baseResolved = resolveAll(base, report, permKey(defaults));
const usable = (t, resolved) => resolved.get(t.path) !== undefined;
if (!report.ok && !LENIENT) fail();

const block = (selector, comment, entries) => entries.length ? `/* ${comment} */\n${selector} {\n${entries.map(([k, v]) => `  ${k}: ${v};`).join("\n")}\n}\n` : "";
const pick = (tokens, resolved, pred) => [...tokens.values()].filter(pred).filter(t => usable(t, resolved)).flatMap(t => declare(t, tokens, resolved));

let css = `/* Adjoin tokens. Generated by scripts/build.mjs from ${RESOLVER}. Do not edit. */\n\n`;
css += block(":root", "Primitives and mode-independent semantics. Primitive vars exist so aliases resolve; consumers must not use them directly.",
  pick(base, baseResolved, t => t.origin.kind === "set" && t.origin.name !== "components"));

for (const m of modifiers) {
  for (const ctx of Object.keys(m.contexts)) {
    const inputs = { ...defaults, [m.name]: ctx };
    const toks = flatten(layers, inputs, report);
    const res = resolveAll(toks, report, permKey(inputs));
    const sel = ctx === m.default ? `:root,\n[data-${m.name}="${ctx}"]` : `[data-${m.name}="${ctx}"]`;
    const entries = pick(toks, res, t => t.origin.kind === "modifier" && t.origin.name === m.name);
    if (m.name === "theme") entries.unshift(["color-scheme", ctx]);
    css += "\n" + block(sel, `${m.name}: ${ctx}${ctx === m.default ? " (default)" : ""}`, entries);
  }
}
css += "\n" + block(`:root,\n[data-theme],\n[data-density]`,
  "Components. Re-declared on every mode container: a var() is computed where it is declared, so without this a nested [data-theme=\"dark\"] would inherit light component values from :root.",
  pick(base, baseResolved, t => t.origin.kind === "set" && t.origin.name === "components"));

// ---------- public API ----------
const publicTokens = [...base.values()].filter(t => !isPrimitive(t) && usable(t, baseResolved));
const paths = publicTokens.map(t => publicPath(t.path)).sort();
const typeOf = Object.fromEntries(publicTokens.map(t => [publicPath(t.path), baseResolved.get(t.path).type]));
const deprecated = publicTokens.filter(t => t.deprecated).map(t => publicPath(t.path));
const perms = permutations(layers);

const valueOf = (r) => {
  if (r.type === "typography") {
    const v = r.value;
    return { fontFamily: fmt("fontFamily", v.fontFamily), fontSize: fmt("dimension", v.fontSize), fontWeight: v.fontWeight, lineHeight: v.lineHeight, letterSpacing: fmt("dimension", v.letterSpacing) };
  }
  return fmt(r.type, r.value);
};
const values = {};
for (const p of perms) {
  const toks = flatten(layers, p, report); const res = resolveAll(toks, report, permKey(p));
  const out = {};
  for (const t of toks.values()) if (!isPrimitive(t) && res.get(t.path)) {
    const v = valueOf(res.get(t.path));
    const feat = t.value && featureOf(t) ? featureOf(t) : (aliasOf(t.value) && featureOf(toks.get(aliasOf(t.value)) ?? {}));
    out[publicPath(t.path)] = feat && typeof v === "object" ? { ...v, fontFeatureSettings: feat } : v;
  }
  values[`${p.theme}/${p.density}`] = out;
}
if (!report.ok && !LENIENT) fail();

const union = xs => xs.length ? xs.map(x => `\n  | ${JSON.stringify(x)}`).join("") : " never";
const types = [...new Set(Object.values(typeOf))].sort();
const dts = `// Generated by scripts/build.mjs. Do not edit.
/** Every public Adjoin token path. Primitives (palette.*, scale.*) are excluded on purpose: an agent can pick a token by meaning, never by raw value. */
export type TokenPath =${union(paths)};

export type TokenType =${union(types)};

/** The DTCG $type of each token. */
export interface TokenTypeMap {
${paths.map(p => `  ${JSON.stringify(p)}: ${JSON.stringify(typeOf[p])};`).join("\n")}
}

export type TokenPathOfType<T extends TokenType> = { [P in TokenPath]: TokenTypeMap[P] extends T ? P : never }[TokenPath];
export type ColorToken = TokenPathOfType<"color">;
export type DimensionToken = TokenPathOfType<"dimension">;
export type TypographyToken = TokenPathOfType<"typography">;
export type NumberToken = TokenPathOfType<"number">;

/** Tokens scheduled for removal. Still valid, but CI warns on every use. */
export type DeprecatedTokenPath =${union(deprecated)};

${modifiers.map(m => `export type ${m.name[0].toUpperCase() + m.name.slice(1)} =${union(Object.keys(m.contexts))};`).join("\n")}

type Kebab<S extends string> = S extends \`\${infer A}.\${infer B}\` ? \`\${A}-\${Kebab<B>}\` : S;
/** The CSS custom property for a token, computed at the type level: CssVar<"color.text.default"> is "var(--adjoin-color-text-default)". */
export type CssVar<P extends TokenPath = TokenPath> = \`var(--adjoin-\${Kebab<P>})\`;

export interface TypographyValue { fontFamily: string; fontSize: string; fontWeight: number | string; lineHeight: number; letterSpacing: string; fontFeatureSettings?: string }
export type TokenValue = string | TypographyValue;
`;

const meta = Object.fromEntries(publicTokens.map(t => [publicPath(t.path), { type: typeOf[publicPath(t.path)], ...(t.description ? { description: t.description } : {}), ...(t.deprecated ? { deprecated: t.deprecated } : {}) }]));
const index = `// Generated by scripts/build.mjs. Do not edit.
import type { TokenPath, TokenType, TokenValue, CssVar, Theme, Density } from "./tokens";
export type * from "./tokens";

export const themes = ${JSON.stringify(Object.keys(modifiers.find(m => m.name === "theme").contexts))} as const satisfies readonly Theme[];
export const densities = ${JSON.stringify(Object.keys(modifiers.find(m => m.name === "density").contexts))} as const satisfies readonly Density[];
export const defaults = ${JSON.stringify(defaults)} as const satisfies { theme: Theme; density: Density };

/** Type and agent-facing description of every public token. */
export const meta = ${JSON.stringify(meta, null, 2)} as const satisfies Record<TokenPath, { type: TokenType; description?: string; deprecated?: string | boolean }>;

const values: Record<\`\${Theme}/\${Density}\`, Record<TokenPath, TokenValue>> = ${JSON.stringify(values)};

/** CSS custom property for a token. Prefer this in styles: it follows the nearest data-theme / data-density container. */
export function cssVar<P extends TokenPath>(path: P): CssVar<P> {
  return \`var(--adjoin-\${path.replaceAll(".", "-")})\` as CssVar<P>;
}

/** Resolved value for one theme × density, for canvas, charts and anywhere CSS vars can't reach. */
export function resolve(path: TokenPath, mode: { theme?: Theme; density?: Density } = {}): TokenValue {
  const { theme = defaults.theme, density = defaults.density } = mode;
  return values[\`\${theme}/\${density}\`][path];
}
`;

const cssVars = { deprecated: Object.fromEntries(publicTokens.filter(t => t.deprecated).map(t => [cssName(t.path), typeof t.deprecated === "string" ? t.deprecated : "scheduled for removal"])), public: [...new Set(publicTokens.map(t => cssName(t.path)))].sort(), primitive: [...base.values()].filter(isPrimitive).map(t => cssName(t.path)).sort() };
// typography sub-properties are public too
for (const t of publicTokens) if (baseResolved.get(t.path).type === "typography") for (const [, c] of [...TYPO_PARTS, [0, "font-feature-settings"]]) cssVars.public.push(`${cssName(t.path)}-${c}`);

mkdirSync(OUT, { recursive: true });
writeFileSync(`${OUT}/tokens.css`, css);
writeFileSync(`${OUT}/tokens.d.ts`, dts);
writeFileSync(`${OUT}/index.ts`, index);
writeFileSync(`${OUT}/css-vars.json`, JSON.stringify(cssVars, null, 2) + "\n");
const skipped = new Set(report.errors.map(e => e.message.replace(/ \((theme|density)=[^)]*\)/, ""))).size;
console.log(`${skipped ? "⚠" : "✓"} built ${paths.length} public tokens × ${perms.length} permutations → ${OUT}/${skipped ? `  (lenient: ${skipped} error(s) skipped; run npm run validate)` : ""}`);

function fail() {
  for (const e of report.errors) console.log(`error    ${e.code}  ${e.message}`);
  console.log("\n✗ build failed. Run `npm run validate` for details, or `--lenient` to emit what resolves.");
  process.exit(1);
}
